### ISSUE TITLE
cleanup functions runs when componenet unmount and not before re-executing the side effect

### ISSUE THREAD

**Issue by mk-emeks** [bloodyowl/reason-react-update#24]
I think current lib approach don't follow React "expected" behavior, I mean:

>  After every re-render with changed dependencies, React will first run the cleanup function (if you provided it) with the old values, and then run your setup function with the new values. After your component is removed from the DOM, React will run your cleanup function.

Source: https://react.dev/reference/react/useEffect#parameters

## Current `rescript-react-update` behavior:

- https://github.com/emeks-studio/rescript-react-restate/blob/main/examples/BasicUsage.res#L1

^ If you execute that example, you would notice that every time the button is click, the action is trigger, but the cleanup function will only run at time of unmounting the component.

## "Raw" React:
- https://github.com/emeks-studio/rescript-react-restate/blob/main/examples/BasicUsage.res#L74

^ Here the clean up is called every time after the button is clicked, and before run the new effect. 

### [extra] Proposed solution (`rescript-react-restate` fork of your lib)

- https://github.com/emeks-studio/rescript-react-restate/blob/main/examples/BasicUsage.res#L36

^ Same as raw react.

Just in case, here there is another example: https://github.com/emeks-studio/rescript-react-restate/blob/main/examples/Counter_SideEffects.res . And some docs about the approach I'm taking: https://github.com/emeks-studio/rescript-react-restate?tab=readme-ov-file#rescript-react-restate

...Btw, the reference to the fork is just to give you ideas, and collect feedback, I would be more than glad to help to provide a fix to your lib if you considered it is an actual issue, and not a design decision you took on purpose. Anyway, awesome lib! and thanks for your time on it =)

**Comment by bloodyowl** [comment]
hi! the design is intentional, as the cleanup is only meant to be run in case the component unmounts (to make sure the component is correctly garbage collected and doesn't run side-effect afterwards).

changing this behavior would make unrelated cleanup functions whenever a new action is triggered (e.g. `A` action cleanup function running when sending a `B` action, which isn't necessarily related).
