### ISSUE TITLE
Typescript/JavaScript support

### ISSUE THREAD

**Issue by allforabit** [bloodyowl/reason-react-update#5]
Would this work with typescript or JavaScript? I see some other libs such as Wonka are written on reason but have a typescript version available. I know it's a super simple lib might be just better to port to typescript as a separate lib.

**Comment by phated** [comment]
@allforabit You can just generate the bindings with https://github.com/reason-association/genType - I believe that is what wonka does too.

**Comment by allforabit** [comment]
OK thanks, I'll have a play around with that.
